interface McpToolDefinition {
  name: string;
  description: string;
  inputSchema: {
    type: 'object';
    properties: Record<string, unknown>;
    required?: string[];
  };
}

interface McpToolExport {
  tools: McpToolDefinition[];
  callTool: (name: string, args: Record<string, unknown>) => Promise<unknown>;
  meter?: { credits: number };
  cost?: Record<string, unknown>;
  provider?: string;
}

/**
 * Business Feeds MCP.
 *
 * Business — industry/trade news, economics, real estate and marketing.
 * CF-robust RSS / Atom / RDF reader over a curated, edge-verified registry; on a
 * Cloudflare egress block it falls back to the rss2json proxy. (Generated by
 * scripts/gen-feeds-packs.mjs from scripts/feeds-registry.mjs — do not hand-edit.)
 */


const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';
const PROXY = 'https://api.rss2json.com/v1/api.json';
const MAX_ITEMS = 50;

interface FeedDef { title: string; url: string; category: string; source: string; description: string }

const FEEDS: Record<string, FeedDef> = {
  forbes: { title: "Forbes Business", url: "https://www.forbes.com/business/feed/", category: "business", source: "forbes.com", description: "Business news & analysis" },
  'business-insider': { title: "Business Insider", url: "https://www.businessinsider.com/rss", category: "business", source: "businessinsider.com", description: "Business, tech & markets news" },
  fortune: { title: "Fortune", url: "https://fortune.com/feed/", category: "business", source: "fortune.com", description: "Business & corporate news" },
  'fast-company': { title: "Fast Company", url: "https://www.fastcompany.com/latest/rss", category: "business", source: "fastcompany.com", description: "Business, innovation & design" },
  adweek: { title: "Adweek", url: "https://www.adweek.com/feed/", category: "marketing", source: "adweek.com", description: "Advertising & marketing news" },
  digiday: { title: "Digiday", url: "https://digiday.com/feed/", category: "marketing", source: "digiday.com", description: "Digital media & marketing" },
  'marketing-dive': { title: "Marketing Dive", url: "https://www.marketingdive.com/feeds/news/", category: "marketing", source: "marketingdive.com", description: "Marketing-industry news" },
  'marginal-revolution': { title: "Marginal Revolution", url: "https://marginalrevolution.com/feed", category: "economics", source: "marginalrevolution.com", description: "Economics blog (Tyler Cowen & Alex Tabarrok)" },
  'project-syndicate': { title: "Project Syndicate", url: "https://www.project-syndicate.org/rss", category: "economics", source: "project-syndicate.org", description: "Global economics & policy commentary" },
  'calculated-risk': { title: "Calculated Risk", url: "https://www.calculatedriskblog.com/feeds/posts/default", category: "economics", source: "calculatedriskblog.com", description: "US economy & housing analysis" },
  inman: { title: "Inman", url: "https://www.inman.com/feed/", category: "real-estate", source: "inman.com", description: "US residential real-estate news" },
  housingwire: { title: "HousingWire", url: "https://www.housingwire.com/feed/", category: "real-estate", source: "housingwire.com", description: "US housing & mortgage-industry news" },
  'hr-dive': { title: "HR Dive", url: "https://www.hrdive.com/feeds/news/", category: "business", source: "hrdive.com", description: "HR & workforce-management news" },
  'supply-chain-dive': { title: "Supply Chain Dive", url: "https://www.supplychaindive.com/feeds/news/", category: "business", source: "supplychaindive.com", description: "Supply-chain & logistics news" },
  'construction-dive': { title: "Construction Dive", url: "https://www.constructiondive.com/feeds/news/", category: "business", source: "constructiondive.com", description: "Construction-industry news" },
  'manufacturing-dive': { title: "Manufacturing Dive", url: "https://www.manufacturingdive.com/feeds/news/", category: "business", source: "manufacturingdive.com", description: "Manufacturing-industry news" },
  'retail-dive': { title: "Retail Dive", url: "https://www.retaildive.com/feeds/news/", category: "business", source: "retaildive.com", description: "Retail-industry news" },
  'grocery-dive': { title: "Grocery Dive", url: "https://www.grocerydive.com/feeds/news/", category: "business", source: "grocerydive.com", description: "Grocery & food-retail news" },
  'waste-dive': { title: "Waste Dive", url: "https://www.wastedive.com/feeds/news/", category: "business", source: "wastedive.com", description: "Waste & recycling-industry news" },
  'packaging-dive': { title: "Packaging Dive", url: "https://www.packagingdive.com/feeds/news/", category: "business", source: "packagingdive.com", description: "Packaging-industry news" },
  'social-media-today': { title: "Social Media Today", url: "https://www.socialmediatoday.com/feeds/news/", category: "marketing", source: "socialmediatoday.com", description: "Social media & digital marketing" },
  'arxiv-econ': { title: "arXiv econ", url: "https://rss.arxiv.org/rss/econ", category: "economics", source: "arxiv.org", description: "arXiv Economics preprints (econ)" },
};

const tools: McpToolExport['tools'] = [
  {
    name: 'list_feeds',
    description: 'List the curated business & industry feeds (id, title, category, source). Optionally filter by category (business, economics, marketing, real-estate) or keyword. Pass an id to read_feed.',
    inputSchema: {
      type: 'object',
      properties: {
        category: { type: 'string', description: 'Filter by category: business, economics, marketing, real-estate.' },
        query: { type: 'string', description: 'Keyword to match in feed title/source/description.' },
      },
    },
  },
  {
    name: 'read_feed',
    description: 'Read a curated business & industry feed by its id (from list_feeds). Returns normalized items (title, link, published, summary). Optionally filter items by keyword.',
    inputSchema: {
      type: 'object',
      properties: {
        feed: { type: 'string', description: 'Curated feed id (from list_feeds).' },
        query: { type: 'string', description: 'Keyword filter over item title/summary.' },
        limit: { type: 'number', description: 'Max items (1-50, default 20).' },
      },
      required: ['feed'],
    },
  },
  {
    name: 'fetch_feed',
    description: 'Fetch and normalize any RSS / Atom / RDF feed by URL. CF-robust: fetches directly and falls back to a proxy if the source blocks the gateway. Use list_feeds first for curated sources.',
    inputSchema: {
      type: 'object',
      properties: {
        url: { type: 'string', description: 'Feed URL, e.g. "https://news.ycombinator.com/rss".' },
        query: { type: 'string', description: 'Keyword filter over item title/summary.' },
        limit: { type: 'number', description: 'Max items (1-50, default 20).' },
      },
      required: ['url'],
    },
  },
];

async function callTool(name: string, args: Record<string, unknown>): Promise<unknown> {
  switch (name) {
    case 'list_feeds':
      return listFeeds(args);
    case 'read_feed': {
      const id = String(args.feed ?? '').trim();
      const def = FEEDS[id];
      if (!def) throw new Error(`Unknown feed "${args.feed}". Use list_feeds to see valid ids.`);
      return readFeed(def.url, args, { id, ...def });
    }
    case 'fetch_feed': {
      const url = String(args.url ?? '').trim();
      if (!/^https?:\/\//i.test(url)) throw new Error('Pass a valid feed `url` (http/https).');
      return readFeed(url, args);
    }
    default:
      throw new Error(`Unknown tool: ${name}`);
  }
}

function listFeeds(args: Record<string, unknown>): unknown {
  const cat = typeof args.category === 'string' ? args.category.trim().toLowerCase() : '';
  const q = typeof args.query === 'string' ? args.query.trim().toLowerCase() : '';
  const feeds = Object.entries(FEEDS)
    .filter(([, d]) => (!cat || d.category === cat) && (!q || `${d.title} ${d.source} ${d.description}`.toLowerCase().includes(q)))
    .map(([id, d]) => ({ id, title: d.title, category: d.category, source: d.source, description: d.description }));
  return { categories: [...new Set(Object.values(FEEDS).map((d) => d.category))].sort(), count: feeds.length, feeds };
}

async function readFeed(url: string, args: Record<string, unknown>, meta?: Record<string, unknown>): Promise<unknown> {
  const limit = clamp(numArg(args.limit, 20), 1, MAX_ITEMS);
  const q = typeof args.query === 'string' ? args.query.trim().toLowerCase() : '';
  const { items, via } = await getFeed(url);
  let out = items;
  if (q) out = out.filter((i) => `${i.title} ${i.summary}`.toLowerCase().includes(q));
  return {
    feed: meta ? { id: meta.id, title: meta.title, source: meta.source } : { url },
    via,
    total_matching: out.length,
    count: Math.min(out.length, limit),
    items: out.slice(0, limit),
  };
}

interface FeedItem { title: string; link: string; published?: string; summary?: string; author?: string; categories?: string[]; id?: string }

async function getFeed(url: string): Promise<{ items: FeedItem[]; via: string }> {
  try {
    const res = await fetch(url, { headers: { 'User-Agent': UA, Accept: 'application/rss+xml, application/atom+xml, application/xml, text/xml, */*' } });
    if (res.ok) {
      const xml = await res.text();
      if (/<(item|entry)[\s>]/i.test(xml)) return { items: parseFeed(xml), via: 'direct' };
    }
  } catch {
    /* fall through to proxy */
  }
  const pres = await fetch(`${PROXY}?rss_url=${encodeURIComponent(url)}&count=${MAX_ITEMS}`, { headers: { 'User-Agent': UA, Accept: 'application/json' } });
  const body = (await pres.json().catch(() => ({}))) as { status?: string; items?: ProxyItem[] };
  if (body.status === 'ok' && Array.isArray(body.items)) {
    return {
      items: body.items.map((i) => ({
        title: clean(i.title), link: i.link || '', published: i.pubDate || undefined,
        summary: clean(i.description)?.slice(0, 500) || undefined, author: i.author || undefined,
        categories: Array.isArray(i.categories) ? i.categories : undefined, id: i.guid || i.link,
      })),
      via: 'proxy',
    };
  }
  throw new Error(`Feed unreachable: ${url} (blocked directly and via proxy). The source may block datacenter egress.`);
}

interface ProxyItem { title?: string; link?: string; pubDate?: string; description?: string; author?: string; categories?: string[]; guid?: string }

function parseFeed(xml: string): FeedItem[] {
  const out: FeedItem[] = [];
  const blocks = xml.match(/<(item|entry)[\s>][\s\S]*?<\/\1>/gi) ?? [];
  for (const b of blocks) {
    const link = extractLink(b);
    out.push({
      title: clean(tag(b, 'title')),
      link,
      published: tag(b, 'pubDate') || tag(b, 'published') || tag(b, 'updated') || tag(b, 'dc:date') || undefined,
      summary: clean(tag(b, 'description') || tag(b, 'summary') || tag(b, 'content:encoded') || tag(b, 'content'))?.slice(0, 500) || undefined,
      author: clean(tag(b, 'dc:creator') || authorName(b)) || undefined,
      categories: cats(b),
      id: tag(b, 'guid') || tag(b, 'id') || link,
    });
  }
  return out;
}

function extractLink(b: string): string {
  const rss = b.match(/<link>([\s\S]*?)<\/link>/i);
  if (rss && rss[1].trim()) return clean(rss[1]);
  const alt = b.match(/<link[^>]*rel=["']alternate["'][^>]*href=["']([^"']+)["']/i) || b.match(/<link[^>]*href=["']([^"']+)["']/i);
  return alt ? alt[1].trim() : '';
}
function authorName(b: string): string {
  const a = b.match(/<author>([\s\S]*?)<\/author>/i);
  if (!a) return '';
  const name = a[1].match(/<name>([\s\S]*?)<\/name>/i);
  return name ? name[1] : a[1];
}
function cats(b: string): string[] | undefined {
  const list: string[] = [];
  for (const m of b.matchAll(/<category[^>]*?(?:term=["']([^"']+)["'][^>]*)?>([\s\S]*?)<\/category>/gi)) {
    const v = clean(m[1] || m[2]);
    if (v) list.push(v);
  }
  for (const m of b.matchAll(/<category[^>]*term=["']([^"']+)["'][^>]*\/>/gi)) list.push(m[1]);
  return list.length ? [...new Set(list)].slice(0, 10) : undefined;
}
function tag(xml: string, name: string): string {
  const m = xml.match(new RegExp(`<${name.replace(':', '\\:')}[^>]*>([\\s\\S]*?)<\\/${name.replace(':', '\\:')}>`, 'i'));
  return m ? unwrap(m[1]) : '';
}
function unwrap(s: string): string {
  const m = s.trim().match(/^<!\[CDATA\[([\s\S]*?)\]\]>$/);
  return (m ? m[1] : s).trim();
}
function clean(s: unknown): string {
  if (typeof s !== 'string') return '';
  return s
    .replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, '$1')
    .replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/<\/?[a-zA-Z][^>]*>/g, ' ')
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(Number(d)))
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&quot;/g, '"').replace(/&#39;|&apos;/g, "'").replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&')
    .replace(/\s+/g, ' ').trim();
}
function numArg(v: unknown, dflt: number): number {
  const n = typeof v === 'number' ? v : typeof v === 'string' ? Number(v) : NaN;
  return Number.isFinite(n) ? n : dflt;
}
function clamp(n: number, lo: number, hi: number): number {
  return Math.max(lo, Math.min(hi, Math.trunc(n)));
}

export default { tools, callTool, meter: { credits: 1 } } satisfies McpToolExport;
